name: Release

on: workflow_dispatch

jobs:
  release-bundle:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'

    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 20.x
      - name: Cache Node.js modules
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-20.x-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-20.x
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
